service: nudge

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  region: ${env:AWS_DEFAULT_REGION}
  environment:
    REGION: ${self:provider.region}
    REPO: ${self:custom.nudge.repo}
    TAG: ${self:custom.nudge.tag}

plugins:
  - serverless-plugin-typescript

custom:
  nudge: ${file(nudge.yml)}

functions:
  nudge:
    handler: src/nudge.handler

resources:
  Description: "nudge slackbot"
