service: nudge

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-plugin-typescript

custom:
  nudge: ${file(nudge.yml)}

functions:
  nudge:
    handler: src/nudge.handler
    environment:
      REPO: ${self:custom.nudge.repo}
      TAG: ${self:custom.nudge.tag}

resources:
  Description: "nudge slackbot"
